# Generated by Django 4.0.3 on 2023-01-16 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_verification_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('verification_code', models.TextField(verbose_name='сюда вставляется сгенерированный код')),
                ('status', models.BooleanField(default=False, verbose_name='активирован?')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подтверждение акканута',
                'verbose_name_plural': 'Подтверждение акканута',
            },
        ),
    ]
