# Generated by Django 4.0.3 on 2023-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0002_teacher_code_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_verification_code',
            name='email',
            field=models.TextField(null=True, verbose_name='сюда вставляется почта'),
        ),
    ]
