# Generated by Django 4.0.3 on 2023-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0003_user_verification_code_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_code_model',
            name='teacher_code_line',
            field=models.IntegerField(verbose_name='сюда вставляется код'),
        ),
    ]
