# Generated by Django 4.0.3 on 2023-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0004_alter_teacher_code_model_teacher_code_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_code_model',
            name='teacher_code_name',
            field=models.CharField(max_length=200, verbose_name='сюда название кода - для чего'),
        ),
    ]
