# Generated by Django 4.0.3 on 2023-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0005_alter_teacher_code_model_teacher_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_verification_code',
            name='email',
            field=models.CharField(max_length=300, null=True, verbose_name='сюда вставляется почта'),
        ),
        migrations.AlterField(
            model_name='user_verification_code',
            name='verification_code',
            field=models.IntegerField(verbose_name='сюда вставляется сгенерированный код'),
        ),
    ]
