# Generated by Django 4.0.3 on 2023-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0006_alter_user_verification_code_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_verification_code',
            name='email',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='сюда вставляется почта'),
        ),
    ]
