# Generated by Django 4.0.3 on 2023-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0007_alter_user_verification_code_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_teacher_start_page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email_contact_start', models.CharField(max_length=200, verbose_name='почта, для контакта')),
                ('text_contact_start', models.IntegerField(verbose_name='текст обращения')),
            ],
            options={
                'verbose_name': 'Обращения с страницы регистрации',
                'verbose_name_plural': 'Обращения с страницы регистрации',
            },
        ),
    ]
