# Generated by Django 4.0.3 on 2023-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0008_contact_teacher_start_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_teacher_start_page',
            name='text_contact_start',
            field=models.TextField(verbose_name='текст обращения'),
        ),
    ]
