# Generated by Django 4.0.3 on 2023-01-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0010_contact_teacher_start_page_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_teacher_start_page',
            name='theme_contact_start',
        ),
    ]
