# Generated by Django 4.0.3 on 2023-01-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0011_remove_contact_teacher_start_page_theme_contact_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filetest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
