# Generated by Django 4.0.3 on 2023-01-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_main', '0012_filetest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filetest',
        ),
    ]
