# Generated by Django 4.0.3 on 2023-01-24 18:04

import accounts_cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='students_files/', validators=[accounts_cabinet.models.file_size]),
        ),
    ]
