# Generated by Django 4.0.3 on 2023-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0004_student_model_user_st_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='about_self',
            field=models.CharField(max_length=200, null=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='show',
            field=models.BooleanField(default=True, verbose_name='статус активен?'),
        ),
    ]
