# Generated by Django 4.0.3 on 2023-01-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_cabinet', '0005_alter_student_model_about_self_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='user_st_login',
        ),
        migrations.AddField(
            model_name='student_model',
            name='user_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='user_id',
            field=models.CharField(max_length=200, null=True, verbose_name='id номер ученика'),
        ),
    ]
