# Generated by Django 4.0.3 on 2023-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0006_remove_student_model_user_st_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student_model',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='имя ученика'),
        ),
    ]
