# Generated by Django 4.0.3 on 2023-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0007_remove_student_model_user_id_student_model_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='show',
            field=models.BooleanField(default=False, verbose_name='статус активен?'),
        ),
    ]
