# Generated by Django 4.0.3 on 2023-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0009_alter_student_model_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='show',
            field=models.BooleanField(verbose_name='статус активен?'),
        ),
    ]
