# Generated by Django 4.0.3 on 2023-01-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0011_remove_student_model_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='show_item',
            field=models.CharField(max_length=200, null=True, verbose_name='показать? yes / no'),
        ),
    ]
