# Generated by Django 4.0.3 on 2023-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0012_student_model_show_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='user_real_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя и фамилия ученика'),
        ),
        migrations.AlterField(
            model_name='student_model',
            name='user_name',
            field=models.CharField(max_length=200, null=True, verbose_name='логин ученика'),
        ),
    ]
