# Generated by Django 4.0.3 on 2023-01-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0013_student_model_user_real_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='class_grade',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер класса с буквой, слитно. Например - 5в. Буква - русская'),
        ),
    ]
