# Generated by Django 4.0.3 on 2023-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0014_alter_student_model_class_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grade_class', models.CharField(max_length=200, null=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Все доступные классы',
                'verbose_name_plural': 'Все доступные классы',
            },
        ),
    ]
