# Generated by Django 4.0.3 on 2023-02-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_cabinet', '0015_student_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='class_grade_true',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_cabinet.student_grades'),
        ),
    ]
