# Generated by Django 4.0.3 on 2023-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_python_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('block_lesson', models.CharField(max_length=200, null=True, verbose_name='блок заданий - введение и т.д.')),
                ('lesson_number', models.CharField(max_length=200, null=True, verbose_name='номер урока по порядку')),
                ('lesson_name', models.CharField(max_length=200, null=True, verbose_name='название урока')),
                ('theory', models.TextField(max_length=3000, null=True, verbose_name='сама теория')),
                ('tasks', models.TextField(max_length=3000, null=True, verbose_name='задания')),
                ('show', models.BooleanField(default=False, verbose_name='показать статью?')),
            ],
            options={
                'verbose_name': 'Курс по Python',
                'verbose_name_plural': 'Курс по Python',
            },
        ),
    ]
