# Generated by Django 4.0.3 on 2023-01-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework_done',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lesson_number', models.CharField(max_length=200, null=True, verbose_name='номер урока по порядку')),
                ('lesson_name', models.CharField(max_length=200, null=True, verbose_name='название урока')),
                ('checked', models.BooleanField(default=False, verbose_name='Дз проверено?')),
                ('theory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_python_model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашние задания',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
