# Generated by Django 4.0.3 on 2023-01-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_html_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homework_done',
        ),
    ]
