# Generated by Django 4.0.3 on 2023-01-30 14:53

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_delete_homework_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework_python',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('real_name', models.CharField(max_length=200, null=True, verbose_name='Фамилия')),
                ('user_login', models.CharField(max_length=200, null=True, verbose_name='Логин')),
                ('class_grade', models.CharField(max_length=20, null=True, verbose_name='Номер класса с буквой')),
                ('note_puntos', models.CharField(max_length=20, null=True, verbose_name='Оценка')),
                ('file_lesson', models.FileField(upload_to=courses.models.get_upload_path, validators=[courses.models.file_size])),
                ('name_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_python_model')),
            ],
            options={
                'verbose_name': 'Выполненные задания - Python',
                'verbose_name_plural': 'Выполненные задания - Python',
            },
        ),
    ]
