# Generated by Django 4.0.3 on 2023-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_homework_python_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_html_model',
            name='tasks',
            field=models.TextField(max_length=6000, null=True, verbose_name='задания'),
        ),
        migrations.AlterField(
            model_name='course_html_model',
            name='theory',
            field=models.TextField(max_length=6000, null=True, verbose_name='сама теория'),
        ),
        migrations.AlterField(
            model_name='course_python_model',
            name='tasks',
            field=models.TextField(max_length=6000, null=True, verbose_name='задания'),
        ),
        migrations.AlterField(
            model_name='course_python_model',
            name='theory',
            field=models.TextField(max_length=6000, null=True, verbose_name='сама теория'),
        ),
    ]
