# Generated by Django 4.0.3 on 2023-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_html_model_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_python',
            name='date_done',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
