# Generated by Django 4.0.3 on 2023-01-31 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_homework_python_date_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_python',
            name='date_done',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
