# Generated by Django 4.0.3 on 2023-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_homework_python_date_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_multimedia_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('block_lesson', models.CharField(max_length=200, null=True, verbose_name='блок заданий - введение и т.д.')),
                ('lesson_number', models.IntegerField(null=True)),
                ('lesson_name', models.CharField(max_length=200, null=True, verbose_name='название урока')),
                ('theory', models.TextField(max_length=6000, null=True, verbose_name='сама теория')),
                ('tasks', models.TextField(max_length=6000, null=True, verbose_name='задания')),
                ('show', models.BooleanField(default=False, verbose_name='показать статью?')),
            ],
            options={
                'verbose_name': 'Курс по Multimedia',
                'verbose_name_plural': 'Курс по Multimedia',
            },
        ),
    ]
