# Generated by Django 4.0.3 on 2023-02-06 18:11

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_course_multimedia_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_multimedia_model',
            name='tasks',
            field=models.TextField(max_length=8000, null=True, verbose_name='задания'),
        ),
        migrations.AlterField(
            model_name='course_multimedia_model',
            name='theory',
            field=models.TextField(max_length=8000, null=True, verbose_name='сама теория'),
        ),
        migrations.CreateModel(
            name='homework_html',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('real_name', models.CharField(max_length=200, null=True, verbose_name='Фамилия')),
                ('user_login', models.CharField(max_length=200, null=True, verbose_name='Логин')),
                ('class_grade', models.CharField(max_length=20, null=True, verbose_name='Номер класса с буквой')),
                ('note_puntos', models.CharField(max_length=20, null=True, verbose_name='Оценка')),
                ('date_done', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('file_lesson', models.FileField(upload_to=courses.models.get_upload_path, validators=[courses.models.file_size])),
                ('name_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_python_model')),
                ('user_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполненные задания - HTML',
                'verbose_name_plural': 'Выполненные задания - HTML',
            },
        ),
    ]
