# Generated by Django 4.0.3 on 2023-02-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_delete_homework_multimedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homework_html',
        ),
    ]
