# Generated by Django 4.0.3 on 2023-02-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_homework_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_python',
            name='show_item',
            field=models.CharField(max_length=20, null=True, verbose_name='Показывать задание?'),
        ),
    ]
