# Generated by Django 4.0.3 on 2023-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_homework_python_show_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_html',
            name='show_item',
            field=models.CharField(max_length=20, null=True, verbose_name='Показывать задание?'),
        ),
        migrations.AddField(
            model_name='homework_multimedia',
            name='show_item',
            field=models.CharField(max_length=20, null=True, verbose_name='Показывать задание?'),
        ),
    ]
